# Import libraries

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable

# Import Faderated learning framework from open mind

In [2]:
import syft as sy

In [3]:
# hooking torch library 

In [4]:
hook = sy.TorchHook(torch)

In [5]:
remote_loc = sy.VirtualWorker(hook, id ='remote_loc')

In [6]:
remote_loc._objects

{}

In [7]:
input_x = Variable(torch.Tensor([i for i in range(12)]).reshape(-1,2))

In [8]:
input_x

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [9]:
input_x.send(remote_loc)

(Wrapper)>[PointerTensor | me:2037586215 -> remote_loc:3832620375]

input_x point towards a pointer Tensor.

In [10]:
input_x.shape

torch.Size([6, 2])

In [11]:
input_y = Variable(torch.Tensor([2.5*i+1 for i in range(6)]).reshape(-1,1))

In [12]:
input_y

tensor([[ 1.0000],
        [ 3.5000],
        [ 6.0000],
        [ 8.5000],
        [11.0000],
        [13.5000]])

In [13]:
input_x.shape, input_y.shape

(torch.Size([6, 2]), torch.Size([6, 1]))

In [14]:
input_y.send(remote_loc)

(Wrapper)>[PointerTensor | me:22516656297 -> remote_loc:21522331614]

Traget (input_y) pointer Tensor where input_y Tensor has been stored

In [15]:
remote_loc._objects

{3832620375: tensor([[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]), 21522331614: tensor([[ 1.0000],
         [ 3.5000],
         [ 6.0000],
         [ 8.5000],
         [11.0000],
         [13.5000]])}

# Intialisation of model, loss funtion and optimzer

In [16]:
model = torch.nn.Linear(2,1)

In [17]:
model.weight

Parameter containing:
tensor([[0.3029, 0.3090]], requires_grad=True)

In [18]:
model.bias

Parameter containing:
tensor([0.4689], requires_grad=True)

In [19]:
criterion = torch.nn.MSELoss()

In [20]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [21]:
model.train()
for epoch in range(10): 
    optimizer.zero_grad()
    pred_y = model(input_x) 
    loss = criterion(pred_y, input_y)  
     
    loss.backward() 
    optimizer.step() 
    print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 0, loss 16.396024703979492
epoch 1, loss 8.00135612487793
epoch 2, loss 3.90641450881958
epoch 3, loss 1.9088653326034546
epoch 4, loss 0.9344160556793213
epoch 5, loss 0.45903000235557556
epoch 6, loss 0.22708602249622345
epoch 7, loss 0.11389175057411194
epoch 8, loss 0.0586252398788929
epoch 9, loss 0.031616196036338806
